version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - jmezach
  ignore:
  - dependency-name: SpecFlow.MsTest
    versions:
    - 3.7.13
    - 3.7.38
  - dependency-name: SpecFlow
    versions:
    - 3.7.13
    - 3.7.38
  - dependency-name: SpecFlow.Tools.MsBuild.Generation
    versions:
    - 3.7.13
    - 3.7.38
  - dependency-name: RavenDb.TestDriver
    versions:
    - 5.1.3
    - 5.1.4
  - dependency-name: RavenDB.Embedded
    versions:
    - 5.1.3
    - 5.1.4
  - dependency-name: Alba
    versions:
    - 4.0.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
  - dependency-name: NSubstitute.Analyzers.CSharp
    versions:
    - 1.0.14
  - dependency-name: Microsoft.Extensions.Logging
    versions:
    - 5.0.0
  - dependency-name: Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer
    versions:
    - 4.2.0
  - dependency-name: Swashbuckle.AspNetCore
    versions:
    - 5.6.3
  - dependency-name: MSTest.TestFramework
    versions:
    - 2.1.2
  - dependency-name: MSTest.TestAdapter
    versions:
    - 2.1.2
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: dotnet/core/aspnet
    versions:
    - 3.1.11
  - dependency-name: dotnet/core/sdk
    versions:
    - 3.1.405
