# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.1.500'
  inputs:
    version: 2.1.500

- script: |
    dotnet tool install --global GitVersion.Tool --version 4.0.1-beta1-50
    dotnet-gitversion /output buildserver

- script: |
    dotnet restore
    dotnet build --configuration $(buildConfiguration) /p:Version=$(GITVERSION_INFORMATIONALVERSION)
    dotnet test Augurk.Test --configuration $(buildConfiguration) --logger trx
    dotnet publish Augurk --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY /p:Version=$(GITVERSION_INFORMATIONALVERSION)
  workingDirectory: 'src'
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)/src/Augurk.Specifications
    contents: "**/?(*.feature|*.md)"
    targetFolder: $(Build.ArtifactStagingDirectory)/features

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)/features
    artifactName: features