# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.1.506'
  inputs:
    version: 2.1.506

- script: |
    dotnet tool install --global GitVersion.Tool --version 4.0.1-beta1-50
    dotnet-gitversion /output buildserver
  displayName: Set version

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: src/Augurk.sln
    workingDirectory: 'src'
  displayName: dotnet restore

- task: DotNetCoreCLI@2
  inputs:
    command: build
    workingDirectory: 'src'
    configuration: $(buildConfiguration)
    arguments: '/p:Version=$(GitVersion.MajorMinorPatch) /p:InformationalVersion=$(GitVersion.InformationalVersion)'
  displayName: dotnet build

- task: DotNetCoreCLI@2
  inputs:
    command: test
    workingDirectory: 'src'
    configuration: $(buildConfiguration)
  displayName: dotnet test

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) /p:Version=$(GitVersion.MajorMinorPatch) /p:InformationalVersion=$(GitVersion.InformationalVersion)'
    zipAfterPublish: true
  displayName: dotnet publish

# - script: |
#     dotnet publish Augurk --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY /p:Version=$GITVERSION_MAJORMINORPATCH /p:InformationalVersion=$GITVERSION_INFORMATIONALVERSION
#   workingDirectory: 'src'

- task: PublishBuildArtifacts@1

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)/src/Augurk.Specifications
    contents: "**/?(*.feature|*.md)"
    targetFolder: $(Build.ArtifactStagingDirectory)/features

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)/features
    artifactName: features